<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE destinos [
<!ELEMENT destinos (destino+)>
<!ELEMENT destino (direccion, localidad, provincia, cp)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT cp (#PCDATA)>
]>

<destinos>
	<destino>
	<direccion>Calle Alcoy n20</direccion>
	<localidad>Madrid</localidad>
	<provincia>Madrid</provincia>
	<cp>7869</cp>
	</destino>

	<destino>
	<direccion>Calle Alicante n32</direccion>
	<localidad>Calpe</localidad>
	<provincia>Alicante</provincia>
	<cp>3145</cp>
	</destino>

	<destino>
	<direccion>Calle Limon n5</direccion>
	<localidad>Valencia</localidad>
	<provincia>Valencia</provincia>
	<cp>3196</cp>
	</destino>

	<destino>
	<direccion>Calle San Policarpo n41</direccion>
	<localidad>Torrevieja</localidad>
	<provincia>Alicante</provincia>
	<cp>3181</cp>
	</destino>

	<destino>
	<direccion>Calle Altea n7</direccion>
	<localidad>Altea</localidad>
	<provincia>Alicante</provincia>
	<cp>3810</cp>
	</destino>

	<destino>
	<direccion>Calle Madrid 10</direccion>
	<localidad>Alicante</localidad>
	<provincia>Alicante</provincia>
	<cp>34523</cp>
	</destino>

	<destino>
	<direccion>Calle Benissa n8</direccion>
	<localidad>Benissa</localidad>
	<provincia>Alicante</provincia>
	<cp>3820</cp>
	</destino>

	<destino>
	<direccion>Calle Gandia n28</direccion>
	<localidad>Gandia</localidad>
	<provincia>Valencia</provincia>
	<cp>44902</cp>
	</destino>

	<destino>
	<direccion>Calle Alemania n3</direccion>
	<localidad>Barcelona</localidad>
	<provincia>Barcelona</provincia>
	<cp>32985</cp>
	</destino>

	<destino>
	<direccion>Calle Mayor</direccion>
	<localidad>Guardamar del Segura</localidad>
	<provincia>Alicante</provincia>
	<cp>4930</cp>
	</destino>

</destinos>